### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by runk**
- Put up-to-date link to the HAL spec
 - Fix `require` statement

### CODE REVIEW

**Comment by runk** [comment]
@jpbochi do you have any ideas what can be wrong with node 0.6 and 0.8 builds?

**Comment by jpbochi** [comment]
@runk apparently, `assertion-error` is not supported in those node versions any more. I'm running the build on `master` again. If that fails, I'll remove those versions from the `travis.yml` file.

I'd like to keep the link to http://stateless.co/hal_specification.html and the one to tools.ietf.org. The first is more didactic.

thanks for the PR

**Comment by jpbochi** [comment]
dang it! the `master` build failed. Now, I see why you removed the `pluck` from there. Can you remove node `0.8` and `0.6` from `.travis.yml` in this PR, please? I'll merge it right away.

**Comment by runk** [comment]
@jpbochi it's all yours :)

**Comment by jpbochi** [comment]
and it's live https://www.npmjs.com/package/halberd

**Pull request merged**
